# Generated by Django 3.1.5 on 2021-02-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImgResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_name', models.CharField(max_length=200)),
                ('authors', models.CharField(max_length=200)),
                ('keywords', models.CharField(max_length=500)),
                ('dateSubmitted', models.DateField(auto_now_add=True)),
                ('link', models.URLField()),
                ('resourceFile', models.BinaryField()),
            ],
        ),
    ]
