# Generated by Django 3.1.5 on 2021-02-08 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorsTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.IntegerField(unique=True)),
                ('author_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='KeywordsMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_id', models.IntegerField()),
                ('keyword', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceIdentification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_id', models.IntegerField()),
                ('resource_name', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='ImgResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateSubmitted', models.DateField(auto_now_add=True)),
                ('link', models.URLField()),
                ('resourceFile', models.BinaryField()),
                ('key_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='keywords', to='WelcomeApp.keywordsmapping')),
                ('resource_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ContributedResources', to='WelcomeApp.resourceidentification')),
            ],
        ),
        migrations.CreateModel(
            name='Contributions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Contribution', to='WelcomeApp.authorstable')),
                ('resource_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ContributedResource', to='WelcomeApp.resourceidentification')),
            ],
        ),
    ]
