# Generated by Django 3.1.5 on 2021-02-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WelcomeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgresource',
            name='resourceFile',
            field=models.BinaryField(editable=True),
        ),
    ]
