# Generated by Django 3.1.5 on 2021-02-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WelcomeApp', '0002_auto_20210209_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgresource',
            name='dateSubmitted',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='imgresource',
            name='resourceFile',
            field=models.ImageField(upload_to=''),
        ),
    ]
