# Generated by Django 3.1.5 on 2021-02-09 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WelcomeApp', '0003_auto_20210209_1624'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='imgresource',
            unique_together={('resource_name', 'authors')},
        ),
    ]
