# Generated by Django 3.1.5 on 2021-02-09 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WelcomeApp', '0004_auto_20210209_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgresource',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='imgresource',
            name='resourceFile',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterUniqueTogether(
            name='imgresource',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='imgresource',
            constraint=models.UniqueConstraint(fields=('resource_name', 'authors'), name='unique_article'),
        ),
    ]
