# Generated by Django 3.1.5 on 2021-02-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WelcomeApp', '0005_auto_20210209_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgresource',
            name='dateSubmitted',
            field=models.DateField(auto_now_add=True),
        ),
    ]
