# Generated by Django 3.1.5 on 2021-02-09 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WelcomeApp', '0006_auto_20210209_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgresource',
            name='link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='imgresource',
            name='resourceFile',
            field=models.ImageField(upload_to=''),
        ),
    ]
