# Generated by Django 3.1.5 on 2021-02-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WelcomeApp', '0007_auto_20210209_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgresource',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
