# Generated by Django 3.1.5 on 2021-02-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WelcomeApp', '0008_auto_20210209_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgresource',
            name='resourceFile',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
