# Generated by Django 3.1.5 on 2021-02-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WelcomeApp', '0012_auto_20210209_1833'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='imgresource',
            name='resourcePresent',
        ),
        migrations.AddConstraint(
            model_name='imgresource',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('link__isnull', True), ('resourceFile__isnull', False)), models.Q(('link__isnull', False), ('resourceFile__isnull', True)), models.Q(('link__isnull', True), ('resourceFile__isnull', True)), _connector='OR'), name='resourcePresent'),
        ),
    ]
